### ISSUE TITLE
feat: %cat command

### ISSUE THREAD

**Issue by fox-lol** [ShaksterNano/borgar#37]
![catnbord](https://user-images.githubusercontent.com/99151137/175439085-f773ffd5-b5b6-47c4-a032-b52105139abc.jpg)

**Comment by ShaksterNano** [comment]
what

**Comment by ShaksterNano** [comment]
Added in https://github.com/ShaksterNano/borgar/commit/4adaeadb0a934bef4fe1327b038d0bb1e376c74b
